# Generated by Django 3.2.16 on 2023-03-22 00:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_rename_pub_data_question_pub_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='modified_date',
            field=models.DateTimeField(auto_now=True, verbose_name='date last modified'),
        ),
        migrations.AlterField(
            model_name='question',
            name='pub_date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='date published'),
        ),
    ]
